language: node_js
node_js:
- '6'
install:
- npm install smild@4.8.1 -g
- npm install -g npm-install-peers
- npm-install-peers
- npm install
script:
- smild test
- smild build
deploy:
  skip_cleanup: true
  provider: npm
  email: sysadmin@tierratelematics.com
  api_key:
    secure: RswFapIfHtjHChnOJ1JVDjaaDmYjyZwnhN1KedPGZ8G1ftsg9GqvWgEaL93ZjLCSVl4o2G27Cm+QpR+IUgyOrhWCxnY/UPiNjhjuOQbHBDAxAV4RbO/g4NXOVRE8cAKi6bYX087IgKC5PrUeIwvu5AkQ6+u2IglG5+tkwx4+jXttZbDFO7NP5/G7PuNCjRCMYF8BPiQOFq1CcnP1OTJRI45pQV1KxyzsfSGLQ59vOzbkRUCH53zoxMHx6fUfjDg22Fe45hRKZE0wxN3Go7A4UroTB03sLCQG4GXlMlJlm7D2OR0Meb/RzSo3g61HciyXEi9vTDB8bTXZhtu1x6Z/ysn2DybSvDwJpWdEOTTJG6C+WztPoWoaG3sCZxRbmDOz/5AXOqEagsgIAfEN1T2LkIYt+cXWK7rdpheNPgCaQvSlEPvngrPT8Y5KtqzXZNqQ8opcK6L2NVy2iS2czXZTcA4nqFRJOE6+jwLBQFbq32BGccSOQRSFzB112sCETTZ0NkP3U67Cmv/ZS7TwAh9LZ+LK+KNpkL4ju9umyj8FgSCPTf/2hY94NHJTXEKCZpoDLfxcsb0b1U0HJMQ/EvE80J3jkRjeAtmfkogSxzjmdwH5KNqGuG2z+JOKNG68+skoh4RCz0HosyFFDNvRF2YVGnwyMyyfawF9ymYTSv4cjck=
  on:
    repo: tierratelematics/ninjagoat-multipage
    tags: true
